import assert from 'node:assert/strict';import{writeFileSync,mkdirSync}from'node:fs';
const base='http://127.0.0.1:3000',run=Date.now();let count=0;const tenants=[];
function session(){const cookies=new Map();return async(path,method='GET',body)=>{const headers={Cookie:[...cookies].map(([k,v])=>k+'='+v).join('; '),Origin:base};if(body)headers['Content-Type']='application/json';const res=await fetch(base+path,{method,headers,body:body?JSON.stringify(body):undefined,redirect:'manual'});for(const cookie of res.headers.getSetCookie()){const [kv]=cookie.split(';'),i=kv.indexOf('=');cookies.set(kv.slice(0,i),kv.slice(i+1))}const text=await res.text();let data;try{data=JSON.parse(text)}catch{data=text}return{status:res.status,data,cookies,headers:res.headers}}}
const check=(condition,label)=>{assert.ok(condition,label);count++;console.log('PASS',label)};
async function login(call,email,password){const csrf=await call('/api/auth/csrf');const form=new URLSearchParams({csrfToken:csrf.data.csrfToken,email,password,callbackUrl:base+'/dashboard',json:'true'});const headers={'Content-Type':'application/x-www-form-urlencoded','X-Auth-Return-Redirect':'1',Cookie:[...csrf.cookies].map(([k,v])=>k+'='+v).join('; '),Origin:base};const r=await fetch(base+'/api/auth/callback/credentials',{method:'POST',headers,body:form,redirect:'manual'});for(const cookie of r.headers.getSetCookie()){const[kv]=cookie.split(';'),i=kv.indexOf('=');csrf.cookies.set(kv.slice(0,i),kv.slice(i+1))}const s=await call('/api/auth/session');check(!!s.data.user,'Login autenticado');}
async function main(){const a=session(),b=session(),anon=session();const health=await anon('/api/health');check(health.status===200&&health.data.status==='ok','Health check confirma aplicação e banco');check((await anon('/api/contacts')).status===401,'API exige autenticação');const password='QA-'+crypto.randomUUID();
for(const [client,suffix]of [[a,'a'],[b,'b']]){const email=`qa-${run}-${suffix}@example.test`;const r=await client('/api/signup','POST',{email,password,fullName:'QA '+suffix,companyName:'QA Test '+suffix+' '+run});if(r.status!==200)console.log(r);check(r.status===200,'Cadastro transacional');tenants.push(r.data.tenantId);await login(client,email,password)}
const aContact=await a('/api/contacts','POST',{fullName:'Contato QA',email:'qa-contact@example.test',phone:'5511999990000',consents:[{channel:'email',purpose:'marketing',granted:true,proof:'QA'}]});if(aContact.status!==201)console.log(aContact.status,aContact.data);check(aContact.status===201,'Criar contato');const cid=aContact.data.id;
check((await b('/api/contacts/'+cid)).status===404,'Empresa B não lê contato A');check((await b('/api/contacts/'+cid,'PUT',{fullName:'Invadido'})).status===404,'Empresa B não altera contato A');
const company=await b('/api/companies','POST',{name:'Empresa B'});check((await a('/api/contacts','POST',{fullName:'Inválido',companyId:company.data.id})).status===400,'Vínculo cruzado rejeitado pela API');
check((await a('/api/settings/invite','POST',{email:'evil@example.test',role:'superadmin'})).status===403,'Convite não eleva para superadmin');
const editedCompany=await b('/api/companies/'+company.data.id,'PUT',{name:'Empresa B revisada',customFields:{segmento:'Serviços'}});check(editedCompany.status===200,'Editar empresa e campos personalizados');const companyRead=await b('/api/companies/'+company.data.id);check(companyRead.data.name==='Empresa B revisada'&&companyRead.data.customFields.segmento==='Serviços','Edição de empresa persistida');
const prod=await a('/api/modules/products','POST',{name:'Serviço QA',code:'QA1',price:100,cost:20});check(prod.status===201,'Catálogo persistido');const pipelines=await a('/api/pipelines');const pipeline=pipelines.data[0];const deal=await a('/api/deals','POST',{title:'Negócio QA',pipelineId:pipeline.id,stageId:pipeline.stages[0].id,contactId:cid,value:200});check(deal.status===201,'Negócio vinculado ao funil e contato');
const dealWithoutContact=await a('/api/deals','POST',{title:'Negócio QA sem contato',pipelineId:pipeline.id,stageId:pipeline.stages[0].id,contactId:null,value:1250});check(dealWithoutContact.status===201&&!dealWithoutContact.data.contactId,'Negócio sem contato é persistido');
check((await a('/api/deals','POST',{title:'Negócio inválido',value:10})).status===400,'Negócio exige funil e etapa pela API');
if(pipeline.stages[1]){check((await a('/api/deals/'+deal.data.id,'PUT',{stageId:pipeline.stages[1].id})).status===200,'Negócio muda de etapa');const moved=await a('/api/deals/'+deal.data.id);check(moved.data.stageId===pipeline.stages[1].id,'Mudança de etapa persiste');await a('/api/deals/'+deal.data.id,'PUT',{stageId:pipeline.stages[0].id})}
check((await a('/api/deals/'+deal.data.id,'PUT',{dealStatus:'won'})).status===200,'Negócio pode ser marcado como ganho');let closedDeal=await a('/api/deals/'+deal.data.id);check(closedDeal.data.dealStatus==='won'&&!!closedDeal.data.closedAt,'Fechamento do negócio persiste');await a('/api/deals/'+deal.data.id,'PUT',{dealStatus:'open'});closedDeal=await a('/api/deals/'+deal.data.id);check(closedDeal.data.dealStatus==='open'&&!closedDeal.data.closedAt,'Negócio reaberto limpa fechamento');
const task=await a('/api/tasks','POST',{title:'Tarefa QA',contactId:cid,dealId:deal.data.id});check(task.status===201,'Tarefa vinculada a contato e negócio');await a('/api/tasks/'+task.data.id,'PUT',{taskStatus:'done'});let taskList=await a('/api/tasks?filter=all');let taskRow=taskList.data.tasks.find(x=>x.id===task.data.id);check(taskRow?.taskStatus==='done'&&!!taskRow.completedAt,'Conclusão da tarefa é persistida');await a('/api/tasks/'+task.data.id,'PUT',{taskStatus:'pending'});taskList=await a('/api/tasks?filter=all');taskRow=taskList.data.tasks.find(x=>x.id===task.data.id);check(taskRow?.taskStatus==='pending'&&!taskRow.completedAt,'Reabertura da tarefa limpa conclusão');
const proposal=await a('/api/modules/proposals','POST',{title:'Proposta QA',dealId:deal.data.id,items:[{productId:prod.data.id,name:'Serviço QA',quantity:2,price:100,discount:10}]});check(proposal.status===201&&Number(proposal.data.total)===180,'Proposta calcula desconto no servidor');
for(let i=0;i<2;i++){const ch=await a('/api/modules/channels','POST',{name:'Web QA '+i,type:'webchat',credentials:{origins:'http://127.0.0.1:3000'}});check(ch.status===201,'Conexão dentro do limite');if(i===0){const conv=await a('/api/conversations','POST',{channelId:ch.data.id,contactId:cid});check(conv.status===200,'Conversa vinculada');const note=await a('/api/messages','POST',{conversationId:conv.data.id,content:'Nota privada',internal:true});check(note.status===200&&note.data.status==='internal','Nota interna persistida')}}
check((await a('/api/modules/channels','POST',{name:'Excedente',type:'webchat',credentials:{}})).status===409,'Essencial bloqueia terceira conexão');
const importResult=await a('/api/import','POST',{resource:'contacts',csv:'nome,email\nImportado,importado@example.test\nImportado,importado@example.test',mapping:{fullName:'nome',email:'email'}});check(importResult.status===200&&importResult.data.created===1&&importResult.data.skipped===1,'CSV elimina duplicação dentro do arquivo');
const badImport=await a('/api/import','POST',{resource:'products',csv:'name,code,price\nInválido,QAB,not-money',mapping:{name:'name',code:'code',price:'price'}});check(badImport.status===400,'Importação inválida sem gravação');
const flow=await a('/api/modules/automations','POST',{name:'QA fluxo',trigger:'contact.created',active:true,definition:{nodes:[{id:'start',data:{kind:'trigger'}},{id:'task',data:{kind:'task',title:'Acompanhar QA'}}],edges:[{source:'start',target:'task'}]}});check(flow.status===201,'Fluxo visual persistido');
check((await a('/api/billing')).status===200,'Portal de assinatura');check((await a('/api/admin')).status===403,'Admin local não acessa painel global');
const noConsent=await b('/api/modules/channels','POST',{name:'Email QA',type:'email',credentials:{token:'not-a-real-token',from:'qa@example.test'}});const campaign=await b('/api/modules/campaigns','POST',{name:'Sem consentimento',channelId:noConsent.data.id,content:'QA'});check((await b('/api/campaigns/action','POST',{id:campaign.data.id,action:'launch'})).status===400,'Campanha sem consentimento não é agendada');
const dashboard=await a('/api/dashboard');check(dashboard.data.openConversations===1,'Painel conta conversas reais');check(dashboard.status===200&&dashboard.data.openDealsCount===2,'Dashboard reflete dados reais');
mkdirSync('.local',{recursive:true});writeFileSync('.local/qa-tenants.json',JSON.stringify(tenants));writeFileSync('.local/http-results.json',JSON.stringify({passed:count,run:new Date().toISOString()},null,2));console.log(`${count} verificações HTTP passaram`);
}
main().catch(e=>{mkdirSync('.local',{recursive:true});writeFileSync('.local/qa-tenants.json',JSON.stringify(tenants));console.error(e);process.exitCode=1});
