 'use client'
import {useEffect,useState} from 'react'
import {api} from '@/components/crm/resource-manager'
import {toast} from 'sonner'
export default function Page(){const [data,setData]=useState<any>(null),[document,setDocument]=useState(''),[busy,setBusy]=useState(false);const load=()=>api('/api/billing').then(setData).catch(e=>toast.error(e.message));useEffect(()=>{load()},[])
 async function choose(plan:string){setBusy(true);try{const r=await api('/api/billing','POST',{plan,document});if(r.url)window.location.assign(r.url);else{toast.info(r.message);load()}}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 return <section className="boss-page"><div className="boss-title"><div><span className="eyebrow">SUA EMPRESA, SEU PLANO</span><h1>Assinatura</h1><p>Cobrança por empresa. Mais previsibilidade para crescer.</p></div></div>{data&&<div className="boss-panel mb-6"><strong>{data.tenant.name}</strong><p>Status: {data.billing?.status} · {data.users} usuários · {data.channels} canais</p><p>Teste até {new Date(data.tenant.trialEndsAt).toLocaleDateString('pt-BR')}</p>{!data.configured&&<p className="note">A cobrança aguarda a configuração da conta Asaas pela administração da plataforma.</p>}</div>}
 <label className="block mb-5">CPF/CNPJ do pagador<input className="boss-input" value={document} onChange={e=>setDocument(e.target.value)}/></label><div className="grid md:grid-cols-2 gap-6">{[['essential','Essencial',299,'3 usuários · 2 canais'],['unlimited','Ilimitado',599,'Usuários e canais ilimitados']].map(([id,name,price,description])=><div className="boss-panel" key={id}><span className="eyebrow">{name}</span><h2 className="text-4xl my-4">R$ {price}<small className="text-sm"> / mês</small></h2><p>{description}</p><p>CRM, campanhas, automações e IA com API própria.</p><button disabled={busy||!data?.configured} className="primary mt-6" onClick={()=>choose(String(id))}>Assinar {name}</button></div>)}</div><p className="note my-4">Consumo dos canais e da API de IA é cobrado pelos fornecedores. Pagamento em ambiente seguro Asaas.</p>
 <div className="boss-panel mt-6"><h2>Faturas</h2>{data?.invoices.map((i:any)=><div key={i.id} className="flex justify-between border-b py-3"><span>{new Date(i.dueAt).toLocaleDateString('pt-BR')} · R$ {i.amount} · {i.status}</span><a href={i.url} target="_blank" rel="noreferrer">Abrir fatura</a></div>)}{!data?.invoices.length&&<p>Ainda não há faturas.</p>}</div>{data?.billing?.subscriptionId&&<button className="secondary mt-6" onClick={async()=>{if(confirm('Cancelar a assinatura e a renovação?'))try{await api('/api/billing','POST',{action:'cancel'});load()}catch(e:any){toast.error(e.message)}}}>Cancelar assinatura</button>}</section>
}
