 'use client'
import {useEffect,useState} from 'react'
import {CustomFieldInputs} from './custom-fields'
import {toast} from 'sonner'
import {Plus,Search,Pencil,Trash2,ArrowUpRight,Package,Download} from 'lucide-react'
import {clientApi as api} from '@/lib/client-api'
export {api}
const definitions:any={
 products:{title:'Produtos e serviços',sub:'Seu catálogo conectado a cada oportunidade.',fields:[['name','Nome'],['code','Código / SKU'],['price','Preço','number'],['cost','Custo','number'],['unit','Unidade'],['description','Descrição','textarea']]},
 proposals:{title:'Propostas comerciais',sub:'Produtos, condições e aceite em um único lugar.',fields:[['title','Título'],['dealId','Negócio','deals'],['validUntil','Validade','date']]},
 channels:{title:'Canais de comunicação',sub:'Conecte suas contas e centralize o atendimento.',fields:[['name','Nome da conexão'],['type','Modalidade','channeltype'],['externalId','Identificador da conta / instância']]},
 campaigns:{title:'Campanhas',sub:'Conversas relevantes para o público certo, com consentimento.',fields:[['name','Nome'],['channelId','Canal','channels'],['tag','Etiqueta do segmento (vazio = todos com consentimento)'],['content','Mensagem (use {{nome}} para personalizar)','textarea'],['template','Nome do template Meta aprovado, sem variáveis'],['scheduledAt','Agendamento','datetime-local']]},
 knowledge:{title:'Base de conhecimento',sub:'Informações da sua empresa para respostas com contexto.',fields:[['title','Título'],['content','Conteúdo','textarea']]},
 agents:{title:'Agentes de IA',sub:'Configure o atendimento e mantenha o controle humano.',fields:[['name','Nome'],['instructions','Instruções','textarea'],['model','Modelo'],['channelId','Canal','channels'],['monthlyLimit','Limite de solicitações/mês','number'],['active','Ativo','checkbox']]},
 'api-keys':{title:'Chaves de API',sub:'Integrações com sistemas externos. A chave é exibida uma única vez.',fields:[['name','Identificação']]},
 'webhook-endpoints':{title:'Webhooks',sub:'Receba eventos assinados. O domínio de destino deve ser autorizado na plataforma.',fields:[['url','URL HTTPS']]},
 audit:{title:'Auditoria',sub:'Histórico de operações da sua empresa.',fields:[]},
 executions:{title:'Execuções',sub:'Histórico e resultado das automações.',fields:[]}
}
const channelTypes:any={whatsapp_official:'WhatsApp oficial · Meta API',whatsapp_session:'WhatsApp por sessão · Evolution (não oficial)',instagram:'Instagram',messenger:'Facebook Messenger',telegram:'Telegram',email:'E-mail · Resend',sms:'SMS · Twilio',webchat:'Chat do site'}
const credentialFields:any={whatsapp_official:['token','appSecret','language'],instagram:['token','appSecret'],messenger:['token','appSecret'],whatsapp_session:['url','token'],telegram:['token'],email:['token','from','webhookKey'],sms:['accountSid','token','from'],webchat:['origins']}
export default function ResourceManager({resource}:{resource:string}){
 const def=definitions[resource], [items,setItems]=useState<any[]>([]),[query,setQuery]=useState(''),[editing,setEditing]=useState<any>(null),[draft,setDraft]=useState<any>({}),[options,setOptions]=useState<any>({}),[busy,setBusy]=useState(false),[detail,setDetail]=useState<any>(null),[page,setPage]=useState(1),[total,setTotal]=useState(0)
 const load=()=>api(`/api/modules/${resource}?page=${page}`).then(d=>{setItems(d.items);setTotal(d.total)}).catch(e=>toast.error(e.message))
 useEffect(()=>{load();api('/api/options').then(setOptions).catch(()=>{})},[resource,page])
 const change=(key:string,value:any)=>setDraft((d:any)=>({...d,[key]:value}))
 function open(item:any=null){setDraft(item?{...item,credentials:{}}:{name:'',type:'whatsapp_official',price:0,cost:0,unit:'un',model:'gpt-4.1-mini',monthlyLimit:100,active:false,items:[],credentials:{}});setEditing(item??{})}
 async function save(e:any){e.preventDefault();setBusy(true);try{const body={...draft};for(const key of ['validUntil','scheduledAt'])if(!body[key])delete body[key];if(resource==='agents'&&!body.channelId)body.channelId=null;const out=await api(`/api/modules/${resource}${editing.id?'/'+editing.id:''}`,editing.id?'PUT':'POST',body);setEditing(null);toast.success('Salvo');if(out.token||out.secret||out.webhookSecret)setDetail(out);await load()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function action(item:any,action:string){try{const out=await api('/api/campaigns/action','POST',{id:item.id,action});if(action==='report')setDetail(out);else toast.success(out.queued?`${out.queued} destinatários agendados`:'Atualizado');load()}catch(e:any){toast.error(e.message)}}
 return <section className="boss-page"><div className="boss-title"><div><span className="eyebrow">BOSS / OPERAÇÃO COMERCIAL</span><h1>{def.title}</h1><p>{def.sub}</p></div>{def.fields.length>0&&<button className="primary" onClick={()=>open()}><Plus size={17}/> Novo registro</button>}</div>
 <div className="boss-toolbar"><Search size={18}/><input aria-label="Pesquisar registros" placeholder="Pesquisar nesta página..." value={query} onChange={e=>setQuery(e.target.value)}/><span>{total} registros</span>{resource==='products'&&<a href="/api/import?resource=products"><Download size={18}/></a>}</div>
 <div className="boss-table-wrap"><table className="boss-table"><thead><tr><th>Registro</th><th>Detalhes</th><th>Status / valor</th><th>Ações</th></tr></thead><tbody>{items.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())).map(item=><tr key={item.id}><td><strong>{item.name??item.title??item.action??item.id.slice(0,8)}</strong><small>{item.code??item.type??new Date(item.createdAt??Date.now()).toLocaleDateString('pt-BR')}</small></td><td>{resource==='channels'?<><span>{channelTypes[item.type]}</span><small className="break-all">{item.webhookUrl}</small></>:resource==='proposals'?<a target="_blank" href={`/proposal/${item.token}`}>Abrir proposta <ArrowUpRight size={13} className="inline"/></a>:resource==='audit'?item.resourceType:resource==='campaigns'?item.tag||'Todos com consentimento':resource==='agents'?item.model:resource==='webhook-endpoints'?item.url:(item.description??item.content??'').slice(0,70)}</td><td>{item.price!==undefined||item.total!==undefined?<strong>{Number(item.price??item.total).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong>:<span className="pill">{item.status??(item.active===false?'Inativo':'Disponível')}</span>}</td><td><div className="flex gap-2 flex-wrap">{def.fields.length>0&&<><button aria-label="Editar" onClick={()=>open(item)}><Pencil size={16}/></button><button aria-label="Excluir" onClick={async()=>{if(confirm('Excluir este registro?'))try{await api(`/api/modules/${resource}/${item.id}`,'DELETE');load()}catch(e:any){toast.error(e.message)}}}><Trash2 size={16}/></button></>}{resource==='campaigns'&&<>{item.status==='draft'&&<button onClick={()=>action(item,'launch')}>Agendar</button>}{['scheduled','running'].includes(item.status)&&<button onClick={()=>action(item,'pause')}>Pausar</button>}{item.status==='paused'&&<button onClick={()=>action(item,'resume')}>Retomar</button>}<button onClick={()=>action(item,'report')}>Relatório</button>{['paused','scheduled','running'].includes(item.status)&&<button onClick={()=>action(item,'cancel')}>Cancelar</button>}</>}{resource==='executions'&&<button onClick={()=>setDetail(item.log)}>Ver etapas</button>}{resource==='channels'&&<button onClick={async()=>{try{const r=await api(`/api/channels/${item.id}/connect`,'POST',{});setDetail(r)}catch(e:any){toast.error(e.message)}}}>Configurar conexão</button>}</div></td></tr>)}</tbody></table>{!items.length&&<div className="boss-empty"><Package size={35}/><h3>Seu próximo passo começa aqui</h3><p>{def.fields.length?'Adicione o primeiro registro para organizar sua operação.':'As atividades aparecerão aqui conforme o uso.'}</p></div>}</div><div className="flex justify-end gap-4 mt-4"><button disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page}</span><button disabled={page*100>=total} onClick={()=>setPage(page+1)}>Próxima</button></div>
 {editing&&<div className="boss-overlay"><form className="boss-modal" onSubmit={save}><div className="flex justify-between"><h2>{editing.id?'Editar':'Novo'} · {def.title}</h2><button type="button" onClick={()=>setEditing(null)}>Fechar</button></div><div className="boss-fields">{def.fields.map(([key,label,type]:any)=><label key={key}>{label}{type==='checkbox'?<input type="checkbox" checked={!!draft[key]} onChange={e=>change(key,e.target.checked)}/>:type==='textarea'?<textarea rows={5} value={draft[key]??''} onChange={e=>change(key,e.target.value)}/>:['channels','deals','channeltype'].includes(type)?<select value={draft[key]??''} onChange={e=>change(key,e.target.value)}><option value="">Selecione</option>{type==='channeltype'?Object.entries(channelTypes).map(([v,l]:any)=><option key={v} value={v}>{l}</option>):(options[type]??[]).map((o:any)=><option key={o.id} value={o.id}>{o.name??o.title}</option>)}</select>:<input type={type??'text'} step={type==='number'?'0.01':undefined} value={type==='date'?draft[key]?.slice(0,10)??'':type==='datetime-local'?draft[key]?.slice(0,16)??'':draft[key]??''} onChange={e=>change(key,type==='number'?Number(e.target.value):e.target.value)}/>}</label>)}</div>
 {resource==='products'&&<CustomFieldInputs entity="products" values={draft.customFields??{}} onChange={v=>change('customFields',v)}/>}
 {resource==='channels'&&<div className="boss-fields"><p className="note">{draft.type==='whatsapp_session'?'Conexão por sessão não oficial, separada da API oficial Meta.':'Tokens ficam criptografados e não voltam a ser exibidos.'}</p>{(credentialFields[draft.type]??[]).map((f:string)=><label key={f}>{({token:'Token / chave da API',appSecret:'Segredo do aplicativo Meta',from:'Remetente',url:'URL do servidor Evolution',origins:'Domínios permitidos (separados por vírgula)',webhookKey:'Chave de assinatura do webhook Resend',accountSid:'Account SID',language:'Idioma do template (pt_BR)'} as any)[f]}<input type={['token','appSecret','webhookKey'].includes(f)?'password':'text'} value={draft.credentials?.[f]??''} onChange={e=>change('credentials',{...draft.credentials,[f]:e.target.value})}/></label>)}</div>}
 {resource==='agents'&&<div className="my-4"><h3>Ações autorizadas</h3>{[['create_task','Criar tarefa'],['handoff','Transferir para humano']].map(([v,l])=><label className="block text-sm my-2" key={v}><input type="checkbox" checked={(draft.allowedActions??[]).includes(v)} onChange={e=>change('allowedActions',e.target.checked?[...(draft.allowedActions??[]),v]:(draft.allowedActions??[]).filter((x:string)=>x!==v))}/> {l}</label>)}</div>}
 {resource==='proposals'&&<div><h3>Itens da proposta</h3>{(draft.items??[]).map((item:any,i:number)=><div key={i} className="proposal-line"><select value={item.productId} onChange={e=>{const product=options.products.find((x:any)=>x.id===e.target.value);change('items',draft.items.map((x:any,j:number)=>j===i?{...x,productId:product.id,name:product.name,price:Number(product.price)}:x))}}><option value="">Produto</option>{(options.products??[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{['quantity','price','discount'].map(k=><label key={k}>{({quantity:'Qtd.',price:'Preço',discount:'Desc. %'} as any)[k]}<input type="number" step="0.01" value={item[k]} onChange={e=>change('items',draft.items.map((x:any,j:number)=>j===i?{...x,[k]:Number(e.target.value)}:x))}/></label>)}<button type="button" onClick={()=>change('items',draft.items.filter((_:any,j:number)=>j!==i))}>×</button></div>)}<button type="button" className="secondary" onClick={()=>change('items',[...(draft.items??[]),{productId:'',name:'',quantity:1,price:0,discount:0}])}>Adicionar produto</button></div>}
 <button className="primary mt-6" disabled={busy}>{busy?'Salvando...':'Salvar'}</button></form></div>}
 {detail&&<div className="boss-overlay"><div className="boss-modal"><h2>Detalhes da operação</h2>{detail.qr&&<img alt="QR de conexão" src={detail.qr}/>}<pre className="whitespace-pre-wrap break-all text-sm my-4">{JSON.stringify({...detail,qr:undefined},null,2)}</pre><button className="primary" onClick={()=>setDetail(null)}>Fechar</button></div></div>}
 </section>
}
