CREATE UNIQUE INDEX IF NOT EXISTS "users_tenant_id_pair" ON "users" ("tenant_id","id");
CREATE UNIQUE INDEX IF NOT EXISTS "teams_tenant_id_pair" ON "teams" ("tenant_id","id");
CREATE UNIQUE INDEX IF NOT EXISTS "companies_tenant_id_pair" ON "companies" ("tenant_id","id");
CREATE UNIQUE INDEX IF NOT EXISTS "contacts_tenant_id_pair" ON "contacts" ("tenant_id","id");
CREATE UNIQUE INDEX IF NOT EXISTS "pipelines_tenant_id_pair" ON "pipelines" ("tenant_id","id");
CREATE UNIQUE INDEX IF NOT EXISTS "stages_tenant_id_pair" ON "stages" ("tenant_id","id");
CREATE UNIQUE INDEX IF NOT EXISTS "deals_tenant_id_pair" ON "deals" ("tenant_id","id");
CREATE UNIQUE INDEX IF NOT EXISTS "tasks_tenant_id_pair" ON "tasks" ("tenant_id","id");
CREATE UNIQUE INDEX IF NOT EXISTS "audit_logs_tenant_id_pair" ON "audit_logs" ("tenant_id","id");
CREATE UNIQUE INDEX IF NOT EXISTS "user_invitations_tenant_id_pair" ON "user_invitations" ("tenant_id","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Product_tenant_id_pair" ON "Product" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Proposal_tenant_id_pair" ON "Proposal" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Channel_tenant_id_pair" ON "Channel" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Conversation_tenant_id_pair" ON "Conversation" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Message_tenant_id_pair" ON "Message" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Automation_tenant_id_pair" ON "Automation" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Execution_tenant_id_pair" ON "Execution" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Campaign_tenant_id_pair" ON "Campaign" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "CampaignRecipient_tenant_id_pair" ON "CampaignRecipient" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Knowledge_tenant_id_pair" ON "Knowledge" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Agent_tenant_id_pair" ON "Agent" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Integration_tenant_id_pair" ON "Integration" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Usage_tenant_id_pair" ON "Usage" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Billing_tenant_id_pair" ON "Billing" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Invoice_tenant_id_pair" ON "Invoice" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "Job_tenant_id_pair" ON "Job" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "ApiKey_tenant_id_pair" ON "ApiKey" ("tenantId","id");
CREATE UNIQUE INDEX IF NOT EXISTS "WebhookEndpoint_tenant_id_pair" ON "WebhookEndpoint" ("tenantId","id");
ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS audit_logs_user_id_tenant_fk;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='teams_supervisor_id_tenant_fk') THEN ALTER TABLE "teams" ADD CONSTRAINT "teams_supervisor_id_tenant_fk" FOREIGN KEY ("tenant_id","supervisor_id") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='companies_responsible_user_id_tenant_fk') THEN ALTER TABLE "companies" ADD CONSTRAINT "companies_responsible_user_id_tenant_fk" FOREIGN KEY ("tenant_id","responsible_user_id") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='companies_created_by_tenant_fk') THEN ALTER TABLE "companies" ADD CONSTRAINT "companies_created_by_tenant_fk" FOREIGN KEY ("tenant_id","created_by") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='contacts_company_id_tenant_fk') THEN ALTER TABLE "contacts" ADD CONSTRAINT "contacts_company_id_tenant_fk" FOREIGN KEY ("tenant_id","company_id") REFERENCES "companies"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='contacts_responsible_user_id_tenant_fk') THEN ALTER TABLE "contacts" ADD CONSTRAINT "contacts_responsible_user_id_tenant_fk" FOREIGN KEY ("tenant_id","responsible_user_id") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='contacts_team_id_tenant_fk') THEN ALTER TABLE "contacts" ADD CONSTRAINT "contacts_team_id_tenant_fk" FOREIGN KEY ("tenant_id","team_id") REFERENCES "teams"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='contacts_merged_into_id_tenant_fk') THEN ALTER TABLE "contacts" ADD CONSTRAINT "contacts_merged_into_id_tenant_fk" FOREIGN KEY ("tenant_id","merged_into_id") REFERENCES "contacts"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='contacts_created_by_tenant_fk') THEN ALTER TABLE "contacts" ADD CONSTRAINT "contacts_created_by_tenant_fk" FOREIGN KEY ("tenant_id","created_by") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='stages_pipeline_id_tenant_fk') THEN ALTER TABLE "stages" ADD CONSTRAINT "stages_pipeline_id_tenant_fk" FOREIGN KEY ("tenant_id","pipeline_id") REFERENCES "pipelines"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='deals_pipeline_id_tenant_fk') THEN ALTER TABLE "deals" ADD CONSTRAINT "deals_pipeline_id_tenant_fk" FOREIGN KEY ("tenant_id","pipeline_id") REFERENCES "pipelines"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='deals_stage_id_tenant_fk') THEN ALTER TABLE "deals" ADD CONSTRAINT "deals_stage_id_tenant_fk" FOREIGN KEY ("tenant_id","stage_id") REFERENCES "stages"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='deals_contact_id_tenant_fk') THEN ALTER TABLE "deals" ADD CONSTRAINT "deals_contact_id_tenant_fk" FOREIGN KEY ("tenant_id","contact_id") REFERENCES "contacts"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='deals_company_id_tenant_fk') THEN ALTER TABLE "deals" ADD CONSTRAINT "deals_company_id_tenant_fk" FOREIGN KEY ("tenant_id","company_id") REFERENCES "companies"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='deals_responsible_user_id_tenant_fk') THEN ALTER TABLE "deals" ADD CONSTRAINT "deals_responsible_user_id_tenant_fk" FOREIGN KEY ("tenant_id","responsible_user_id") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='deals_created_by_tenant_fk') THEN ALTER TABLE "deals" ADD CONSTRAINT "deals_created_by_tenant_fk" FOREIGN KEY ("tenant_id","created_by") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tasks_assigned_to_tenant_fk') THEN ALTER TABLE "tasks" ADD CONSTRAINT "tasks_assigned_to_tenant_fk" FOREIGN KEY ("tenant_id","assigned_to") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tasks_contact_id_tenant_fk') THEN ALTER TABLE "tasks" ADD CONSTRAINT "tasks_contact_id_tenant_fk" FOREIGN KEY ("tenant_id","contact_id") REFERENCES "contacts"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tasks_deal_id_tenant_fk') THEN ALTER TABLE "tasks" ADD CONSTRAINT "tasks_deal_id_tenant_fk" FOREIGN KEY ("tenant_id","deal_id") REFERENCES "deals"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tasks_completed_by_tenant_fk') THEN ALTER TABLE "tasks" ADD CONSTRAINT "tasks_completed_by_tenant_fk" FOREIGN KEY ("tenant_id","completed_by") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tasks_created_by_tenant_fk') THEN ALTER TABLE "tasks" ADD CONSTRAINT "tasks_created_by_tenant_fk" FOREIGN KEY ("tenant_id","created_by") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_invitations_invited_by_tenant_fk') THEN ALTER TABLE "user_invitations" ADD CONSTRAINT "user_invitations_invited_by_tenant_fk" FOREIGN KEY ("tenant_id","invited_by") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='Message_conversationId_tenant_fk') THEN ALTER TABLE "Message" ADD CONSTRAINT "Message_conversationId_tenant_fk" FOREIGN KEY ("tenantId","conversationId") REFERENCES "Conversation"("tenantId","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='CampaignRecipient_campaignId_tenant_fk') THEN ALTER TABLE "CampaignRecipient" ADD CONSTRAINT "CampaignRecipient_campaignId_tenant_fk" FOREIGN KEY ("tenantId","campaignId") REFERENCES "Campaign"("tenantId","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='Proposal_dealId_tenant_fk') THEN ALTER TABLE "Proposal" ADD CONSTRAINT "Proposal_dealId_tenant_fk" FOREIGN KEY ("tenantId","dealId") REFERENCES "deals"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='Conversation_channelId_tenant_fk') THEN ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_channelId_tenant_fk" FOREIGN KEY ("tenantId","channelId") REFERENCES "Channel"("tenantId","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='Conversation_contactId_tenant_fk') THEN ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_contactId_tenant_fk" FOREIGN KEY ("tenantId","contactId") REFERENCES "contacts"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='Conversation_dealId_tenant_fk') THEN ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_dealId_tenant_fk" FOREIGN KEY ("tenantId","dealId") REFERENCES "deals"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='Conversation_assignedToId_tenant_fk') THEN ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_assignedToId_tenant_fk" FOREIGN KEY ("tenantId","assignedToId") REFERENCES "users"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='Campaign_channelId_tenant_fk') THEN ALTER TABLE "Campaign" ADD CONSTRAINT "Campaign_channelId_tenant_fk" FOREIGN KEY ("tenantId","channelId") REFERENCES "Channel"("tenantId","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='CampaignRecipient_contactId_tenant_fk') THEN ALTER TABLE "CampaignRecipient" ADD CONSTRAINT "CampaignRecipient_contactId_tenant_fk" FOREIGN KEY ("tenantId","contactId") REFERENCES "contacts"("tenant_id","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='Execution_automationId_tenant_fk') THEN ALTER TABLE "Execution" ADD CONSTRAINT "Execution_automationId_tenant_fk" FOREIGN KEY ("tenantId","automationId") REFERENCES "Automation"("tenantId","id"); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='Agent_channelId_tenant_fk') THEN ALTER TABLE "Agent" ADD CONSTRAINT "Agent_channelId_tenant_fk" FOREIGN KEY ("tenantId","channelId") REFERENCES "Channel"("tenantId","id"); END IF; END $$;
CREATE OR REPLACE FUNCTION check_team_tenant() RETURNS trigger AS $$ BEGIN IF NOT EXISTS (SELECT 1 FROM teams t JOIN users u ON u.tenant_id=t.tenant_id WHERE t.id=NEW.team_id AND u.id=NEW.user_id) THEN RAISE EXCEPTION 'Cross-tenant team membership'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS team_tenant_guard ON team_members;
CREATE TRIGGER team_tenant_guard BEFORE INSERT OR UPDATE ON team_members FOR EACH ROW EXECUTE FUNCTION check_team_tenant();
